name: iosApp
configs:
  Debug: debug
  Release: release
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-spm.git
    from: 4.2.0
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    dependencies:
      - package: Lottie
    sources: 
      - iosApp
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: 3BAP3ARWXJ
        PRODUCT_MODULE_NAME: iosApp
        PRODUCT_BUNDLE_IDENTIFIER: orgIdentifier.iosApp
